HW 2 module
js-tasks-ru/jsbasic-20211108_info32 pull request #4
Opened 2021-12-01 18:12 UTC by GandraburGhenadie

2021-12-01 18:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-02 13:21 UTC, SinimaWath requested changes

2021-12-02 13:21 UTC, SinimaWath commented on 2-module/2-task/index.js
> +    if (key) { }
Блок кода в if у тебя пустой, поэтому нет никакого смысла оставлять этот if

2021-12-02 20:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-09 20:08 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-10 15:24 UTC, SinimaWath approved these changes
все ок!

2021-12-10 15:25 UTC, merged